name: 'DingTalk Notification'
description: 'Actions completed publishing DingTalk notification'
inputs:
  requestUrl:  # id of input
    description: 'Get the before data'
    required: true
#    default: 'World'
outputs:
  data_json: # id of output
    description: 'Pre release data'
runs:
  using: 'node20'
  main: 'index.js'
