name: 'DingTalk Notification'
description: 'Actions completed publishing DingTalk notification'
inputs:
  ding_talk_url: # id of input
    description: 'ding_talk_url notification address'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
