name: 'DingTalk Notification'
description: 'Actions completed publishing DingTalk notification'
continue-on-error: true
inputs:
  request_url: # id of input
    description: 'curl Get the before data'
    required: true
  validate: # id of input
    description: 'validate data'
    required: false
  ding_talk_url: # id of input
    description: 'DingTalk notification address'
    required: false
  footer_text: # id of output
    description: 'Notes Rich Text'
    required: false
#    default: 'World'
runs:
  using: 'node20'
  main: 'index.js'
